name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - name: Cache Metrics
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/
      #     key: metrics-cache
      #     restore-keys: |
      #       metrics-cache
            
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          config_timezone: America/Denver
          base: header, activity
          base_indepth: yes
          config_order: base.header, base.activity+community, followup
          extras_css: |
            svg {
              color: silver !important;
            }
            
            h1, h2, h3 {
              color: LightSeaGreen !important;
              font-weight: bold;
            }

            .language.details small{
              color: #929fad !important;
            }

            .legend .field:nth-last-child(2),
            .legend .field:nth-last-child(1) {
                display:none;
            }

            h2.field {
              overflow: hidden;
              height: 0;
              width: 0;
            }

            section > small {
              display:none;
            }
          # extras_js: |
          #   const svg = document.querySelectorAll("svg")[0]
          #   if (svg) {
          #     const height = svg.getAttribute("height")
          #     if (height) {
          #       svg.setAttribute("height", String(parseInt(height) - 60));
          #     }
          #   }

          plugin_languages: yes
          # plugin_languages_aliases: tsx:React
          plugin_languages_colors: python:#ffde57
          plugin_languages_skipped: SD
          # plugin_languages_other: yes
          plugin_languages_threshold: 1%
          plugin_languages_sections: recently-used, most-used
          plugin_languages_categories: markup, programming
          plugin_languages_details: lines, percentage
          # plugin_languages_indepth: yes
          # commits_authoring: blake vandercar, bvandercar, bvandercar-vt, bvandercar@outlook.com, blake.vandercar@validatek.com
          # plugin_languages_analysis_timeout_repositories: 15
          # plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 365
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          # debug: yes
          # debug_print: yes
